### ISSUE TITLE
Add additional UserRoleProviders 

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/fiat#30]
I've been seeing various users in Slack saying they can't/won't use Google Apps for Work or Github Teams for role provider. Some have proposed adding LDAP as both an authentication and authorization provider (aka UserRoleProvider).

If you'd like to see this or any other kind of provider, please make yourself known by commenting on this issue.

**Comment by veeresh1982** [comment]
@ttomsu : I am interested to know more about this development. Can you please let me know the updates and timeline on supporting fiat with LDAP for both authentication/authorization.

**Comment by ttomsu** [comment]
I've been working on getting the rest of the infrastructure integrated with Fiat, but realize additional user role providers will be necessary. That being said, I'd welcome a contribution to Gate that uses Spring Security LDAP and or an LDAP-based `UserRoleProvider` :-)

**Comment by chongkong** [comment]
I guess SAML group is currently working?

**Comment by ttomsu** [comment]
@chongkong - yes, see http://www.spinnaker.io/v1.0/docs/securing-spinnaker

**Comment by JohnTheodore** [comment]
We won't use gapps/github, though we would use ldap for sure!

**Comment by TheDigitalNinja** [comment]
I would love to see LDAP support.

To answer @JohnTheodore I would like to be able to plug directly into AWS Simple AD

**Comment by tony612** [comment]
I really want this feature. And, what if we don't have SAML or LDAP? We build a auth service by ourself in our company to login to our inner services and manage the access. Is this possible for our situation? Maybe a webhook can be implemented(like k8s http://kubernetes.io/docs/admin/authorization/)?

**Comment by rafaelcaricio** [comment]
Would be nice to be possible to use OAuth2 user scopes for authorization.

**Comment by ttomsu** [comment]
Any brave souls out there interested in testing the initial LDAP functionality? I don't know if or how much different the ActiveDirectory work would be, but would be curious to talk with AD users too.

**Comment by mtweten** [comment]
I've recently been working to try out the LDAP functionality in gate/fiat (we have an AD setup), and I think the only thing we'd need to be able to support the structure we have is some additional fields to the LDAP configuration. 

Some explanation of our setup: The DNs for our users have a CN of the formatted full name, e.g. `CN=Smith,John,OU=Users,OU=<some office location>,OU=Offices`, and the user id is in the sAMAccountName attribute. Using the userDnPattern field as it exists now, users in our setup would need to login with that full CN (Smith,John) instead of their user id. 

Another complication for us is that our Users are organized by office location (e.g. `OU=Users,OU=<some office location>,OU=Offices`). Since the userDnPattern needs to form a full DN, we would need to hardcode a single office location in.

The changes would be pretty small - basically adding a userSearchBase and userSearchFilter. I've got an example of how that might go for [fiat](https://github.com/mtweten/fiat/commit/8f6affbfea7f9645ca64e772fb7576f2b3fac076) and [gate](https://github.com/mtweten/gate/commit/57e3e0972a28b17f6be84d92ddfa690e99c12b83).

Our fiat config could then be something like:
```
auth:
  groupMembership:
    service: ldap
    ldap:
      url: ldap://ldaphost/DC=mydomain,DC=com
      managerDn: <user>
      managerPassword: <pass>
      userSearchBase: ou=Offices
      userSearchFilter: (&(objectClass=person)(sAMAccountName={0}))
      groupSearchBase: ou=Offices
      groupSearchFilter: (&(objectClass=group)(member={0}))
      groupRoleAttributes: cn
```

Would that be a feature you'd be interested in supporting?
